name: ذخیره تغییرات

on:
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest
    steps:
      - name: ساخت فایل index.html از محتوای پنل
        run: |
          cat > index.html << 'EOF'
          {{ github.event.client_payload.content }}$
          EOF

      - name: ذخیره تغییرات
        run: |
          git config user.name "Admin Bot"
          git config user.email "admin@site.com"
          git add index.html
          git commit -m "بروزرسانی محتوا از پنل ادمین" || echo "تغییری وجود ندارد"
          git push
